ballerina-platform/module-ballerina-jballerina.java.arrays

.github/workflows/build-master.yml
README.md
java.arrays-ballerina/build.gradle
java.arrays-ballerina/src/java.arrays/java_array_utils.bal

$subject
- Add test configurations
- Add README
- Rename master build -> build
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
- SLP4
- Java 8

Add README and fix public type issue

---

java.arrays-ballerina/build.gradle
java.arrays-ballerina/src/java.arrays/java_array_utils.bal
java.arrays-ballerina/src/java.arrays/tests/java_array_handle_tests.bal
java.arrays-ballerina/src/java.arrays/tests/java_array_passing_tests.bal
java.arrays-ballerina/src/java.arrays/util_functions.bal

$subject
ballerina-platform/ballerina-lang#25637
- SLP4
- Java 8
- macOS

Add class type support

---

java.arrays-test-utils/src/main/java/org/ballerinalang/stdlib/java.arrays/testutils/JHandler.java

Migrate jBallerina Runtime APIs

---

.github/workflows/pull-request.yml
java.arrays-ballerina/src/java.arrays/util_functions.bal

Fixes #5 
- SLP4
- Java 8
- macOS

Make internal functions isolated

---

.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
build.gradle
java.arrays-ballerina/build.gradle

Add release workflow

---

.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
build.gradle
java.arrays-ballerina/build.gradle

This PR will add a new release workflow to java.array module

Add release workflow to java.array module

---

.github/workflows/build-master.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
build.gradle
gradle.properties

Update build config and move dependent modules to snapshot

---

java.arrays-ballerina/Ballerina.toml

- $subject
- https://github.com/ballerina-platform/module-ballerina-java.arrays/issues/13

Update Java version in the Ballerina.toml

---

java.arrays-test-utils/src/main/java/module-info.java
java.arrays-test-utils/src/main/java/org/ballerinalang/stdlib/java.arrays/testutils/JHandler.java

Refactor ballerina runtime api usages

Migrate ballerina runtime apis

---

README.md

Update README.md issue and projects section

---

gradle.properties

Upgrade ballerina version

---

.github/workflows/pull-request.yml

subtask of https://github.com/ballerina-platform/ballerina-standard-library/issues/569

Change PR action to user the user tokens

---

jarrays-ballerina/build.gradle

Enable balo packaging in jarrays

---

jarrays-ballerina/tests/java_array_handle_tests.bal
jarrays-ballerina/tests/java_array_passing_tests.bal

$title
- macOS
- SLP9
- Java11

Fix new language breaking changes

---

build.gradle

Remove old snapshot repo

---

jarrays-ballerina/build.gradle

> Update ballerina command to bal command

Update ballerina command to bal command

---

jarrays-ballerina/jarray_utils.bal
jarrays-ballerina/tests/java_array_handle_tests.bal
jarrays-ballerina/tests/java_array_passing_tests.bal
jarrays-ballerina/util_functions.bal

Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Change the name of the `java` langlib module to `jballerina.java`

---

java.arrays-ballerina/build.gradle

Avoid running tests when publishing

---

java.arrays-ballerina/build.gradle

> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476

Change ballerina archive extension to bala

---

java.arrays-ballerina/tests/java_array_handle_tests.bal

Address the changes here https://github.com/ballerina-platform/ballerina-lang/pull/28483
Rename the java:jObjToString->java:toString
https://github.com/ballerina-platform/ballerina-lang/pull/28483

Rename the java:jObjToString->java:toString

---

.github/workflows/publish-release.yml
build.gradle
gradle.properties
java.arrays-ballerina/build.gradle

- Subtask of https://github.com/ballerina-platform/ballerina-standard-library/issues/957
- Bump the next version to a minor alpha version
- Improve the build scripts and actions to publish the artifacts to the Ballerina central during a release

Enable publishing to the Ballerina central during the release

---

build.gradle
java.arrays-ballerina/build.gradle

Otherwise, it will publish without an updated Ballerina.toml file.

Re-order Build Tasks to Publish to the Ballerina Central

---

java.arrays-ballerina/build.gradle

Avoid publishing to central for SNAPSHOT builds

---

.github/workflows/build-master.yml
.github/workflows/pull-request.yml
java.arrays-ballerina/build.gradle

Remove publishing code-coverage testable JAR and archive JSON

---

.github/workflows/publish-release.yml
README.md
java.arrays-ballerina/build.gradle

Change the org name ballerina->ballerinax

---

java.arrays-ballerina/build.gradle

> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763

Add extracted bala in the zip artifact

---

java.arrays-ballerina/build.gradle

> Add -c flag to build command
> Related to https://github.com/ballerina-platform/ballerina-lang/pull/29032

Add -c flag to build command

---

codecov.yml

Remove Codecov Fixes

---

build.gradle
jballerina.java.arrays-ballerina/build.gradle

Strip stdlib dependency version

---

build-config/checkstyle/build.gradle
build.gradle
gradle.properties
jballerina.java.arrays-ballerina/build.gradle

Standardize build script of Ballerina module

Apply Gradle Ballerina plugin for Ballerina module build script

---

jballerina.java.arrays-ballerina/Module.md
jballerina.java.arrays-ballerina/Package.md

Improve the API docs, module MD, and package MD

---

jballerina.java.arrays-ballerina/build.gradle

Update flag for coverage format from '--jacoco-xml' to '--coverage-format=xml'

Update flag for coverage format

---

jballerina.java.arrays-ballerina/jarray_utils.bal
jballerina.java.arrays-ballerina/tests/java_array_handle_tests.bal
jballerina.java.arrays-ballerina/tests/java_array_passing_tests.bal

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1441

Make APIs isolated

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
build.gradle
jballerina.java.arrays-ballerina/Package.md

Related to:
ballerina-platform/ballerina-release#547 
ballerina-platform/ballerina-standard-library#1462

Improve actions, Gradle, and Package.md

---

.github/workflows/build-timestamped-master.yml

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2362

Escape MD files and the docs directory from master build

---

ballerina/tests/java_array_handle_tests.bal
ballerina/tests/java_array_passing_tests.bal

Remove unnecessary checkpanic usage with variables

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties

Reverts ballerina-platform/module-ballerina-jballerina.java.arrays#395

Revert "[Automated] Sync master after 1.2.1 release"

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml

Upgrade the distribution version to 2201.0.1

---

.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/trivy-scan.yml
test-utils/build.gradle

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2902
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2802

Change the scan type of the Trivy scan and remove ballerina-core

---

ballerina/Ballerina.toml
build-config/resources/Ballerina.toml

Upgrade the distribution to 2201.0.4

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties

Update Language version to 2201.0.4

---

.github/workflows/central-publish.yml

Add missing `sed` command for multiple central environments support

---

.github/workflows/build-with-bal-test-graalvm.yml

Fix codecov

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Bump minor version & update distribution

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml

update github workflow

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
README.md
ballerina/Ballerina.toml
build-config/resources/Ballerina.toml
gradle.properties
test-utils/build.gradle

Migrate to Java 21

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties

Update module versions for U11

---

build-config/resources/Ballerina.toml
gradle.properties

Update dependency versions for U11

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Prepare for update 12

---

ballerina/jarray_utils.bal

Related issue: https://github.com/ballerina-platform/ballerina-library/issues/7736

Fix the API documentation
